Electro-Shop/Electro-Shop/Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Electro_Shop.Areas.Identity.Data;

namespace Electro_Shop.Models
{
    public class Order
    {
        [Key]
        public int OrderID { get; set; }
        [Required]
        public string UserID { get; set; }
        [Required]
        public string TimeStamp { get; set; }
    }
}

Electro-Shop/Electro-Shop/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Electro_Shop.Models
{
    public class Product
    {
        [Key]
        public int Id { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public double Price { get; set; }
        public string Description { get; set; }
        public Category Category { get; set; }
        public int SalesCounter { get; set; }
        public int InStock { get; set; }
        public Uri PathToImage { get; set; }
        public Supplier Supplier { get; set; }
    }
}

Electro-Shop/Electro-Shop/Models/Supplier.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Electro_Shop.Models
{
    public class Supplier
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

Electro-Shop/Electro-Shop/Controllers/ContactUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Electro_Shop.Data;
using Electro_Shop.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Electro_Shop.Controllers
{
    public class ContactUsController : Controller
    {
        private readonly ILogger<ContactUsController> _logger;
        private readonly BranchContext _context;
        private readonly ContactUsContext _Contactcontext;


        public ContactUsController(ILogger<ContactUsController> logger, BranchContext context,ContactUsContext Ccontext)
        {
            _logger = logger;
            _context = context;
            _Contactcontext = Ccontext;

        }

        public IActionResult Index()
        {
            var branches = _context.branches.ToList();
            return View(branches);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromForm] ContactUsSubmit submit)
        {
            if (ModelState.IsValid)
            {
                _Contactcontext.Add(submit);
                await _Contactcontext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(submit);
        }

    }
}

Electro-Shop/Electro-Shop/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Electro_Shop.Models;
using Electro_Shop.Data;
using Electro_Shop.Areas.Identity.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace Electro_Shop.Controllers
{
    public class OrdersController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ProductContext _ProductContext;
        private readonly ShoppingCartContext _ShoppingCartContext;
        private readonly OrdersContext _OrderContext;
        private readonly SignInManager<ApplicationUser> _SignInManager;
        private readonly UserManager<ApplicationUser> _UserManager;

        public OrdersController(ILogger<HomeController> logger, ProductContext Productcontext, UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> SignInManager, ShoppingCartContext shoppingcart, OrdersContext orders)
        {
            _logger = logger;
            _ProductContext = Productcontext;
            _UserManager = userManager;
            _ShoppingCartContext = shoppingcart;
            _SignInManager = SignInManager;
            _OrderContext = orders;
        }

        public IActionResult PastOrders()
        {

            var pastOrders = new PastOrdersView();
            pastOrders.UserID = _UserManager.GetUserId(User);
            pastOrders.OrdersView = new List<OrderView>();


            var allMyOrders = _OrderContext.Orders.Where(x => x.UserID == pastOrders.UserID).ToList();

            foreach (var order in allMyOrders)
            {
                var tempPastOrder = new OrderView()
                {
                    Order = order
                };
                tempPastOrder.OrderLines = new List<OrderLine>();
                var ThisOrderLines = _OrderContext.OrderLines.Where(x => x.UserID == pastOrders.UserID && x.OrderID == order.OrderID).ToList();
                foreach (var line in ThisOrderLines)
                {
                    tempPastOrder.OrderLines.Add(line);
                    tempPastOrder.PricePaid += line.FullPrice;
                }
                pastOrders.OrdersView.Add(tempPastOrder);
            }

            return View(pastOrders);
        }

        public async Task<IActionResult> Reorder(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order_id = await _OrderContext.Orders.FirstOrDefaultAsync(m => m.OrderID == id);
            if (order_id == null)
            {
                return NotFound();
            }

            var allMyOrderLines = _OrderContext.OrderLines.Where(x => x.OrderID == order_id.OrderID).ToList();

            foreach (var line in allMyOrderLines)
            {
                var ShoppingCartLine = new ShoppingCart
                {
                    ProductID = line.ProductID,
                    Quantity = line.Quantity,
                    UserID = line.UserID
                };
                await Create(ShoppingCartLine);
                }
            return RedirectToAction("Index", "ShoppingCart");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CartId ,UserID, , ProductID, Quantity")] ShoppingCart NewLine)
        {

            if (ModelState.IsValid)
            {
                for (int i = 0; i < NewLine.Quantity; i++)
                {
                    ShoppingCart OneNewLine = new ShoppingCart
                    {
                        ProductID = NewLine.ProductID,
                        UserID = NewLine.UserID,
                        Quantity = 1
                    };
                    _ShoppingCartContext.Add(OneNewLine);
                    await _ShoppingCartContext.SaveChangesAsync();
                }

                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
}
}

Electro-Shop/Electro-Shop/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Electro_Shop.Data;
using Electro_Shop.Models;

namespace Electro_Shop.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ProductContext _context;

        public ProductsController(ProductContext context)
        {
            _context = context;
        }

        // GET: Products
        public async Task<IActionResult> Index()
        {
            return View(await _context.Product.ToListAsync());
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Brand,Model,Price,Description,SalesCounter,InStock,PathToImage")] Product product)
        {
            if (ModelState.IsValid)
            {
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Brand,Model,Price,Description,SalesCounter,InStock,PathToImage")] Product product)
        {
            if (id != product.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Product.FindAsync(id);
            _context.Product.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Product.Any(e => e.Id == id);
        }
    }
}

Electro-Shop/Electro-Shop/Controllers/SuppliersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Electro_Shop.Data;
using Electro_Shop.Models;

namespace Electro_Shop.Controllers
{
    public class SuppliersController : Controller
    {
        private readonly SupplierContext _context;

        public SuppliersController(SupplierContext context)
        {
            _context = context;
        }

        // GET: Suppliers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Supplier.ToListAsync());
        }

        // GET: Suppliers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var supplier = await _context.Supplier
                .FirstOrDefaultAsync(m => m.Id == id);
            if (supplier == null)
            {
                return NotFound();
            }

            return View(supplier);
        }

        // GET: Suppliers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Suppliers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                _context.Add(supplier);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(supplier);
        }

        // GET: Suppliers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var supplier = await _context.Supplier.FindAsync(id);
            if (supplier == null)
            {
                return NotFound();
            }
            return View(supplier);
        }

        // POST: Suppliers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Supplier supplier)
        {
            if (id != supplier.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(supplier);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SupplierExists(supplier.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(supplier);
        }

        // GET: Suppliers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var supplier = await _context.Supplier
                .FirstOrDefaultAsync(m => m.Id == id);
            if (supplier == null)
            {
                return NotFound();
            }

            return View(supplier);
        }

        // POST: Suppliers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var supplier = await _context.Supplier.FindAsync(id);
            _context.Supplier.Remove(supplier);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SupplierExists(int id)
        {
            return _context.Supplier.Any(e => e.Id == id);
        }
    }
}

Electro-Shop/Electro-Shop/Areas/AdminCenter/Views/Admin/Categories.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model IEnumerable<Electro_Shop.Models.Category>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-controller="Categories" asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    <a asp-controller="Categories" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-controller="Categories" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Electro-Shop/Electro-Shop/Areas/AdminCenter/Views/Admin/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Administration Center</h1>
<div class="col-md-6 col-sm-6">
    <div class="panel panel-default">
        <div class="panel-heading"><h4>Admin Controls</h4></div>
        <div class="panel-body">
            <div class="row">
                <link rel="stylesheet" href="~/css/bestsellers.css" />
                <div class="col-xs-4 col-md-3 col-lg-2"><a href="/Admin/Products" class="btn btn-default center-block">Products</a></div>
                <div class="col-xs-4 col-md-3 col-lg-2"><a href="/Admin/Categories" class="btn btn-default center-block">Categories</a></div>
                <div class="col-xs-4 col-md-3 col-lg-2"><a href="/Admin/Suppliers" class="btn btn-default center-block">Suppliers</a></div>
                <!--<div class="col-xs-4 col-md-3 col-lg-2">-->@*<a href="/Admin/Users" class="btn btn-default center-block">Users</a>*@<!--</div>-->
                <div class="col-xs-4 col-md-3 col-lg-2"><a href="/Admin/Messages" class="btn btn-default center-block">Messages</a></div>
                <div class="col-xs-4 col-md-3 col-lg-2"><a href="/Admin/Orders" class="btn btn-default center-block">Orders</a></div>
            </div>
            <hr>
            <hr>
        </div>
    </div>
</div>

Electro-Shop/Electro-Shop/Areas/AdminCenter/Views/Admin/Messages.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model IEnumerable<Electro_Shop.Models.ContactUsSubmit>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Messages</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IssueWith)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(model => item.Id)
            </td>
            <td>
                @Html.DisplayFor(model => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(model => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(model => item.Email)
            </td>
            <td>
                @Html.DisplayFor(model => item.PhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(model => item.IssueWith)
            </td>
            <!--<td>-->
            @*<a asp-controller="ContactUs" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |*@
            @*<a asp-controller="ContactUs" asp-action="Delete" asp-route-id="@item.Id">Delete</a>*@
            @*</td>*@
        </tr>
        }
    </tbody>
</table>

Electro-Shop/Electro-Shop/Areas/AdminCenter/Views/Admin/Orders.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model IEnumerable<Electro_Shop.Models.OrderLine>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Orders</h1>

@*<p>
    <a asp-controller="Orders" asp-action="Create">Create New</a>
</p>*@
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.OrderID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FullPrice)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.OrderID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FullPrice)
            </td>
            @*<td>
            <a asp-controller="Orders" asp-action="Edit" asp-route-id="@item.OrderID">Edit</a> |
            <a asp-controller="Orders" asp-action="Delete" asp-route-id="@item.OrderID">Delete</a>
        </td>*@
        </tr>
        }
    </tbody>
</table>

Electro-Shop/Electro-Shop/Areas/AdminCenter/Views/Admin/Products.cshtml
@model IEnumerable<Electro_Shop.Models.Product>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Products</h1>

<p>
    <a asp-controller="Products" asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Brand)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Model)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SalesCounter)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InStock)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PathToImage)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Brand)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Model)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td dir="rtl">
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SalesCounter)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.InStock)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PathToImage)
                </td>
                <td>
                    <a asp-controller="Products" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    @*<a asp-controller="Products" asp-action="Details" asp-route-id="@item.Id">Details</a> |*@
                    <a asp-controller="Products" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Electro-Shop/Electro-Shop/Areas/AdminCenter/Views/Admin/Suppliers.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model IEnumerable<Electro_Shop.Models.Supplier>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Suppliers</h1>

<p>
    <a asp-controller="Suppliers" asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    <a asp-controller="Suppliers" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-controller="Suppliers" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>